# Generated by Django 3.1.5 on 2021-01-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
